"""Tests for Gardena Sileno Minimo 250 (deviceType=29, deviceVariant=4).

The frames in this file were captured with Wireshark from the official
Husqvarna app authenticating against a real Sileno Minimo 250 with PIN 1111.
They form the reference for the warmup sequence the firmware requires before
it accepts EnterOperatorPin.
"""

import binascii
import json
import unittest
from importlib.resources import files
from unittest.mock import AsyncMock

from automower_ble.models import MowerModels
from automower_ble.protocol import BLEClient, Command, ResponseResult


# Channel ID generated by the official app during the captured session;
# the bytes appear on the wire as e2 15 3c 57 (little-endian uint32).
SILENO_CHANNEL_ID = 0x573C15E2


class TestSilenoMinimoFrames(unittest.TestCase):
    """Byte-for-byte parity with frames captured from the official app."""

    def setUp(self):
        with files("automower_ble").joinpath("protocol.json").open("r") as f:
            self.protocol = json.load(f)

    def test_get_model_request_matches_capture(self):
        command = Command(SILENO_CHANNEL_ID, self.protocol["GetModel"])
        self.assertEqual(
            binascii.hexlify(command.generate_request()),
            b"02fd1000e2153c57016200af5a1209000000b703",
        )

    def test_keep_alive_request_matches_capture(self):
        command = Command(SILENO_CHANNEL_ID, self.protocol["KeepAlive"])
        self.assertEqual(
            binascii.hexlify(command.generate_request()),
            b"02fd1000e2153c57016200af421202000000d903",
        )

    def test_set_obstacle_avoidance_request_matches_capture(self):
        command = Command(
            SILENO_CHANNEL_ID, self.protocol["SetObstacleAvoidanceEnabled"]
        )
        self.assertEqual(
            binascii.hexlify(command.generate_request(enabled=0)),
            b"02fd1100e2153c57015f00afec1403000100001803",
        )

    def test_enter_operator_pin_1111_matches_capture(self):
        command = Command(SILENO_CHANNEL_ID, self.protocol["EnterOperatorPin"])
        self.assertEqual(
            binascii.hexlify(command.generate_request(code=1111)),
            b"02fd1200e2153c57011800af38120400020057043e03",
        )

    def test_obstacle_avoidance_response_returns_invalid_id(self):
        """Sileno Minimo has no obstacle avoidance; firmware replies INVALID_ID
        but the request still has to be issued for the warmup to work."""
        command = Command(
            SILENO_CHANNEL_ID, self.protocol["SetObstacleAvoidanceEnabled"]
        )
        response = bytearray.fromhex(
            "02fd1100e2153c57015f01afec1403000700006d03"
        )
        # Result byte (offset 16) is 7 = INVALID_ID; validation must reject it.
        self.assertFalse(command.validate_command_response(response))
        self.assertEqual(response[16], ResponseResult.INVALID_ID.value)
        # The opcode declares no response payload, so parse_response is None.
        self.assertIsNone(command.parse_response(response))

    def test_decode_get_model_response_identifies_sileno_minimo_250(self):
        command = Command(SILENO_CHANNEL_ID, self.protocol["GetModel"])
        response = command.parse_response(
            bytearray.fromhex("02fd1300e2153c57012501af5a1209000002001d041003")
        )
        self.assertEqual(response, {"deviceType": 29, "deviceVariant": 4})

        info = MowerModels[(response["deviceType"], response["deviceVariant"])]
        self.assertEqual(info.manufacturer, "Gardena")
        self.assertEqual(info.model, "SILENO Minimo 250")

    def test_enter_operator_pin_response_is_ok(self):
        command = Command(SILENO_CHANNEL_ID, self.protocol["EnterOperatorPin"])
        response = bytearray.fromhex(
            "02fd1100e2153c57015f01af38120400000000ab03"
        )
        # Result byte 0 = OK; the captured PIN exchange succeeded.
        self.assertTrue(command.validate_command_response(response))
        self.assertEqual(response[16], ResponseResult.OK.value)


class TestSilenoConnectFlow(unittest.IsolatedAsyncioTestCase):
    """The Sileno Minimo only accepts EnterOperatorPin after a specific
    sequence of post-handshake calls. Verify _run_warmup issues them in the
    same order the official app does, with the same payloads."""

    async def test_warmup_issues_get_model_keep_alive_obstacle_avoidance(self):
        client = BLEClient(SILENO_CHANNEL_ID, "00:00:00:00:00:00")
        sent = []

        async def fake_request_response(request):
            sent.append(bytes(request))
            # Synthesize a benign empty response so the warmup loop continues.
            # Use the SetObstacleAvoidanceEnabled NOT_ALLOWED response shape
            # with result=0 to keep validation happy for callers that check.
            return bytearray.fromhex(
                "02fd1100e2153c57015f01af00000000000000ee03"
            )

        client._request_response = AsyncMock(side_effect=fake_request_response)

        await client._run_warmup()

        self.assertEqual(len(sent), 3)
        self.assertEqual(
            binascii.hexlify(sent[0]),
            b"02fd1000e2153c57016200af5a1209000000b703",  # GetModel
        )
        self.assertEqual(
            binascii.hexlify(sent[1]),
            b"02fd1000e2153c57016200af421202000000d903",  # KeepAlive
        )
        self.assertEqual(
            binascii.hexlify(sent[2]),
            b"02fd1100e2153c57015f00afec1403000100001803",  # SetObstacleAvoidance(0)
        )

    async def test_warmup_swallows_no_response(self):
        """A flaky warmup call must not abort the connection — the firmware
        often returns INVALID_ID for SetObstacleAvoidanceEnabled and the
        library's request/response layer surfaces that as None on timeout."""
        client = BLEClient(SILENO_CHANNEL_ID, "00:00:00:00:00:00")
        client._request_response = AsyncMock(return_value=None)

        # Should complete without raising and call _request_response 3 times.
        await client._run_warmup()
        self.assertEqual(client._request_response.await_count, 3)

    async def test_warmup_continues_after_exception(self):
        """If one warmup call blows up (e.g. unknown opcode locally), the
        remaining warmup calls and the subsequent PIN call must still run."""
        client = BLEClient(SILENO_CHANNEL_ID, "00:00:00:00:00:00")
        calls = 0

        async def flaky(request):
            nonlocal calls
            calls += 1
            if calls == 2:
                raise RuntimeError("boom")

        client._request_response = AsyncMock(side_effect=flaky)
        await client._run_warmup()
        self.assertEqual(calls, 3)


class TestSilenoModelLookup(unittest.TestCase):
    def test_29_4_is_sileno_minimo_250(self):
        info = MowerModels[(29, 4)]
        self.assertEqual(info.manufacturer, "Gardena")
        self.assertEqual(info.model, "SILENO Minimo 250")


if __name__ == "__main__":
    unittest.main()
